server {
    listen 80;
    listen [::]:80;
    server_name hub.example.edu;

    access_log /var/log/nginx/hydro-league-access.log;
    error_log /var/log/nginx/hydro-league-error.log;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/acme;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 503;
    }
}
